### API request examples (using vscode REST Client)

@baseUrl = http://localhost:4001
@testAccountId = MyProduct10
@testEmail = demo10@gmail.com
@testPassword = demo1010

### List Posts (with author info)

POST {{baseUrl}}
Content-Type: application/json
X-Request-Type: GraphQL

query {
  feed {
    id
    title
    content
    published
    author {
      id
      name
      email
    }
  }
}

### Register - Sign Up

POST {{baseUrl}}
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  signup(accountId: "{{testAccountId}}", name: "Full Name", email: "{{testEmail}}", password: "{{testPassword}}") {
    token
  }
}

### Login

POST {{baseUrl}}
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  login(accountId: "{{testAccountId}}", email: "{{testEmail}}", password: "{{testPassword}}") {
    token
  }
}

### Verify Email

POST {{baseUrl}}
Content-Type: application/json
X-Request-Type: GraphQL

mutation {
  verifyEmail(accountId: "{{testAccountId}}", email: "{{testEmail}}", emailVerificationToken: "") {
    token
  }
}